### Read Entities
GET http://localhost:4004/odata/v4/reporting
###
GET http://localhost:4004/alpv4/webapp/odata/v4/reporting/$metadata?sap-language=DE
### Returns:
### HTTP/1.1 404 Not Found
GET http://localhost:4004/alp/webapp/odata/v2/reporting/$metadata?sap-value-list=all&sap-language=DE
###
GET http://localhost:4004/odata/v4/reporting/$metadata

###
POST http://localhost:4004/odata/v4/reporting/loadDataFromMock
Content-Type: application/json

{}
###
GET {{$dotenv kyma_url}}/odata/v2/support/
###
GET {{$dotenv kyma_url}}/odata/v2/incidentws/
###
GET {{$dotenv kyma_url}}/odata/v2/incidentws/MessageHeaderSet
    ?$top=2
    &$select=Pointer
###
POST {{$dotenv kyma_url}}/odata/v4/reporting/loadDataFromMock
Content-Type: application/json

{}

###
POST https://07fc19abtrial-dev-sap-support-message-reporting-srv.cfapps.eu10.hana.ondemand.com/odata/v4/reporting/loadDataFromMock
Content-Type: application/json

{}
###
POST http://localhost:4004/odata/v4/reporting/loadDataFromSAP
Content-Type: application/json

{}
###
POST http://localhost:4004/odata/v4/reporting/loadDataFromMeSapCom
Content-Type: application/json

{}

###
GET http://localhost:4004/odata/v4/reporting/MessageHeaderSet
    ?$top=2
    &$select=Pointer
    &$count=true
    &$expand=to_MessageAlogSet($select=ActionTxt)

###
GET http://localhost:4004/odata/v4/reporting/MessageHeaderSet
    ?$top=2
    &$expand=to_MessageAlogSet($apply=groupby((Pointer),aggregate(numberOfLogs with sum as TotalNumberOfLogs)))
### Returns
# Allowed query option expected

###
GET http://localhost:4004/odata/v4/reporting/MessageHeaderSet/$count
###
GET http://localhost:4004/odata/v4/reporting/MessageAlogSet
    ?$top=2

###
GET http://localhost:4004/odata/v4/reporting/MessageAlogSet
    ?$filter=(Pointer eq '002075129400001469512021')
    &$orderby=Aetstmp

###
GET http://localhost:4004/odata/v4/reporting/MessageAlogSet/$count
###
GET http://localhost:4004/odata/v4/reporting/MessageHeaderSet
    ?$apply=aggregate(numberOfMessages with sum as numberOfMessagesTotal)
###
GET http://localhost:4004/odata/v4/reporting/MessageHeaderSetDraft
    ?$apply=aggregate(numberOfMessages with sum as numberOfMessagesTotal)
###
GET http://localhost:4004/odata/v4/reporting/MessageHeaderSet
    ?$apply=groupby((PriorityTxt),aggregate(numberOfMessages with sum as numberOfMessagesTotal))

###
GET http://localhost:4004/odata/v4/reporting/MessageHeaderSet
    ?$apply=groupby((PriorityTxt),aggregate($count as childCount,numberOfMessages with sum as sumQuantity))
###
GET http://localhost:4004/odata/v4/reporting/MessageHeaderSet
    ?$apply=groupby((StatusTxt),aggregate(numberOfMessages with sum as numberOfMessagesTotal))

###
GET http://localhost:4004/odata/v4/reporting/MessageAlogSet
    ?$apply=groupby((NameTxt),aggregate(numberOfLogs with sum as TotalNumberOfLogs))

###
GET http://localhost:4004/odata/v4/reporting/MessageAlogSet
    ?$apply=groupby((Pointer),aggregate(numberOfLogs with sum as TotalNumberOfLogs))
###
GET http://localhost:4004/odata/v4/reporting/MessageContactsSet

###
GET http://localhost:4004/odata/v4/reporting/MessageAlogView

###
GET http://localhost:4004/odata/v4/reporting/PriorityTxtVH
###
GET http://localhost:4004/odata/v4/reporting/StatusTxtVH
###
GET http://localhost:4004/odata/v4/reporting/StatusVH

###
GET http://localhost:4004/odata/v4/reporting/SystemIdVH
###
GET http://localhost:4004/odata/v2/reporting/
###
GET http://localhost:4004/odata/v2/reporting/MessageHeaderSet?$select=numberOfMessages&$inlinecount=allpages

###
GET http://localhost:4004/odata/v2/reporting/MessageHeaderSet
    ?$inlinecount=allpages
    &$select=Status,numberOfMessages
###
GET http://localhost:4004/odata/v2/reporting/MessageHeaderSet(aggregation'{"key":{"StatusTxt":"Not%20Sent%20to%20SAP","PriorityTxt":"Very%20High"},"value":["StatusTxt","PriorityTxt","numberOfMessages"],"filter":"((((StatusTxt%20eq%20'Not%20Sent%20to%20SAP'))))"}')

###
GET http://localhost:4004/odata/v4/reporting/CaseList
    ?$top=10
    &$count=true
