###
GET https://me.sap.com/backend/odata/support/$metadata
Cookie: {{$dotenv cookie}}
###
GET https://me.sap.com/backend/odata/support/CaseList/$count
Cookie: {{$dotenv cookie}}
###
GET https://me.sap.com/backend/odata/support/CaseList
  ?$top=10
Accept: application/json
Cookie: {{$dotenv cookie}}
