###
GET https://launchpad.support.sap.com/services/odata/incidentws/MessageHeaderSet
  ?$inlinecount=allpages&$filter=((Source%20eq%20%27ALL%27)and%20(Status%20eq%20%273%27%20or%20Status%20eq%20%275%27%20or%20Status%20eq%20%27N%27%20or%20Status%20eq%20%27M%27%20or%20Status%20eq%20%27R%27%20or%20Status%20eq%20%27S%27%20or%20Status%20eq%20%27C%27%20or%20Status%20eq%20%271%27)%20and%20(LastUpdate%20eq%20%27ALL%27))
  &$skip=0
  &$top=10
  &$format=json
  &$select=Csinsta,CompKey,PriorityTxt,Pointer,SystemType,SWType,Erftstmp,Aetstmp,Closetstmp
Cookie: {{$dotenv cookie}}

###
GET https://launchpad.support.sap.com/services/odata/incidentws/MessageAlogSet
  ?$filter=(Pointer%20eq%20%27002075129400001469512021%27)
  &$format=json
  &$select=Uname,Pointer,CrInsta,Aetstmp,Lfnr,Service,Servicetyp,Aenam,Tabname,Alobject,OldVal,NewVal,AeDate,AeTime,DayTxt,ActionTxt,OldTxt,NewTxt,UserTimezone
Cookie: {{$dotenv cookie}}
