general:
steps:
  mtaBuild:
    platform: 'CF'
    mtarName: sap-support-message-reporting-cf.mtar
  cloudFoundryDeploy:
    apiEndpoint: https://api.cf.eu10.hana.ondemand.com/
    mtaPath: ./sap-support-message-reporting-cf.mtar
    org: csw
    space: dev
    cfNativeDeployParameters: -f
    deployTool: mtaDeployPlugin