---
apiVersion: v1
kind: Service
metadata:
  name: whoami
  labels:
    app: whoami
spec:
  ports:
    - name: http
      port: 80
  selector:
    app: whoami
    tier: frontend
---
apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  labels:
    app: whoami
  name: whoami
spec:
  service:
    host: whoami
    name: whoami
    port: 80
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
    - path: /.*
      methods: ["GET"]
      accessStrategies:
        - handler: noop
      mutators:
        - handler: noop
---
    apiVersion: v1
    kind: Secret
    metadata:
      name: whoami-secret
    type: opaque
    stringData:
      VCAP_SERVICES: >
        {          
        }
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: whoami
  labels:
    app: whoami
spec:
  selector:
    matchLabels:
      app: whoami
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: whoami
        tier: frontend
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - image: containous/whoami
        name: whoami
        imagePullPolicy: "Always"
        ports:
        - containerPort: 80
          name: http
        envFrom:
        - secretRef:
            name: whoami-secret