name: cf-build-and-deploy-dev

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: pwd
        run: pwd
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
      - name: Check node version
        run: node --version
      - name: Install MTA Build Tool
        run: npm install -g mbt
      - name: Install Packages
        run: npm install ci
      - name: MTA build
        uses: SAP/project-piper-action@master
        with:
          command: mtaBuild
      - name: Upload archive file
        uses: actions/upload-artifact@v3
        with:
          name: mta
          path: sap-support-message-reporting-cf.mtar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: dev
      # url:
    env:
      CF_API: https://api.cf.eu10.hana.ondemand.com/
      CF_ORG: csw
      CF_SPACE: dev
      CF_USERNAME: ${{ secrets.PIPER_USERNAME }}
      CF_PASSWORD: ${{ secrets.PIPER_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: mta
      - name: Display structure of downloaded files
        run: ls -R
      - name: CF Deploy
        id: deploy
        uses: ./.github/actions/cf-deploy
        with:
          createspace: false
          mtafile: ./sap-support-message-reporting-cf.mtar
#          findurl_command: 'cf html5-list -di sflight-destination-service -u'

# Can't get it to work as CF CLI with deploy plugin needs to be installed
#      - name: cloudFoundryDeploy
#        uses: SAP/project-piper-action@master
#        with:
#          command: cloudFoundryDeploy
#        env:
#          PIPER_username: ${{ secrets.PIPER_USERNAME }}
#          PIPER_password: ${{ secrets.PIPER_PASSWORD }}
