name: cf-deploy-production

on: workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      # url:
    env:
      CF_API: https://api.cf.eu10.hana.ondemand.com/
      CF_ORG: csw
      CF_SPACE: production
      CF_USERNAME: ${{ secrets.PIPER_USERNAME }}
      CF_PASSWORD: ${{ secrets.PIPER_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download latest release
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: sap-support-message-reporting-cf.mtar
      #      - name: Download CF artifact
      #        uses: dawidd6/action-download-artifact@v2
      #        with:
      #          workflow: build-mta-cf.yml
      #          workflow_conclusion: success
      #          name: mta
      - name: Display structure of downloaded files
        run: ls -R
      - name: CF Deploy
        id: deploy
        uses: ./.github/actions/cf-deploy
        with:
          createspace: false
          mtafile: ./sap-support-message-reporting-cf.mtar
